/* APK-ONLY NATIVE UPDATE FLOW
 * Uses the Android DownloadManager bridge generated by the APK workflows.
 * Web/Windows are not changed.
 */
(function(){
  'use strict';
  var native=window.AndroidUpdater;
  if(!native)return;
  var pollTimer=null,downloadedId=0;
  function status(id){try{return JSON.parse(native.getStatus(String(id))||'{}')}catch(e){return {status:'error',message:e.message||String(e)}}}
  function stopPoll(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
  function installNow(){
    if(!downloadedId)return toast('File update belum siap.');
    try{
      var r=native.installApk(String(downloadedId));
      if(r==='permission')toast('Izinkan TokoKasirLussal memasang aplikasi dari sumber ini, lalu tekan Install Update lagi.');
      else if(r!=='ok')toast('Tidak dapat membuka installer: '+(r||'error'));
    }catch(e){toast('Gagal membuka installer: '+(e.message||e))}
  }
  var originalSet=window.setUpdateModal;
  window.setUpdateModal=function(state,info){
    originalSet.apply(this,arguments);
    if(state==='done'){
      var accept=document.getElementById('updateAcceptBtn'),later=document.getElementById('updateLaterBtn');
      if(accept){accept.disabled=false;accept.textContent='Install Update';accept.onclick=installNow}
      if(later){later.disabled=false;later.textContent='Nanti';later.onclick=function(){closeUpdateModal()}}
      var msg=document.getElementById('updateMessage');
      if(msg)msg.textContent='Download selesai. Apakah Anda ingin memasang update sekarang?';
    }
  };
  window.startUpdateDownload=function(){
    var info=window.__latestUpdateInfo;
    if(!info||!info.url)return toast('Link update tidak tersedia.');
    var accept=document.getElementById('updateAcceptBtn');
    if(accept){accept.disabled=true;accept.textContent='Mengunduh...'}
    setUpdateModal('downloading',info);
    updateProgress(0,'Menyiapkan download...','Menghubungkan ke server update...');
    stopPoll();
    try{
      downloadedId=Number(native.downloadApk(info.url, info.version||'latest'));
      if(!downloadedId)throw new Error('Android DownloadManager tidak mengembalikan ID download.');
    }catch(e){
      console.error('native APK download',e);closeUpdateModal();toast('Gagal memulai download: '+(e.message||e));return;
    }
    pollTimer=setInterval(function(){
      var s=status(downloadedId);
      if(s.total>0)updateProgress((s.received/s.total)*100,'Mengunduh update...',((s.received/1048576).toFixed(1)+' / '+(s.total/1048576).toFixed(1)+' MB'));
      else updateProgress(5,'Mengunduh update...','Menunggu data dari server...');
      if(s.status==='success'){
        stopPoll();updateProgress(100,'Download selesai','File update sudah tersimpan di perangkat.');
        setUpdateModal('done',info);window.__downloadedUpdateId=downloadedId;
      }else if(s.status==='failed'||s.status==='error'){
        stopPoll();closeUpdateModal();toast('Gagal mengunduh update: '+(s.message||'periksa koneksi internet.'));
      }
    },500);
  };
  window.addEventListener('beforeunload',stopPoll);
})();
