const CONFIG=window.APP_CONFIG||{url:'',key:''};
let sb=null,currentUser=null,profile=null,products=[],agents=[],receivables=[],sales=[],users=[],purchases=[],cart=[],purchaseCart=[],priceProduct=null,selectedProductImage='';
const $=id=>document.getElementById(id),rp=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3000)}
function requireConfig(){if(!CONFIG.url||!CONFIG.key){toast('Isi config.js dengan Supabase URL dan publishable/anon key.');throw Error('Supabase config belum diisi')}}
async function ensureSession(){requireConfig();if(!sb)sb=supabase.createClient(CONFIG.url,CONFIG.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'tokokasirherbal-auth'}});let s=await sb.auth.getSession();if(s.error)throw s.error;const existing=s.data?.session;if(existing?.user?.is_anonymous===true)return existing;if(existing){await sb.auth.signOut({scope:'local'});}let r=await sb.auth.signInAnonymously();if(r.error)throw Error('Login otomatis Supabase gagal: '+r.error.message);if(!r.data?.session)throw Error('Supabase tidak mengembalikan sesi.');return r.data.session}
let loginMode='kasir';
function setLoginMode(mode){loginMode=mode;const isAdmin=mode==='admin';$('loginKasirBtn')?.classList.toggle('primary',!isAdmin);$('loginKasirBtn')?.classList.toggle('secondary',isAdmin);$('loginAdminBtn')?.classList.toggle('primary',isAdmin);$('loginAdminBtn')?.classList.toggle('secondary',!isAdmin);$('passwordField')?.classList.toggle('hidden',!isAdmin);$('loginTitle')?.textContent=isAdmin?'Login Admin':'Login Kasir';$('loginHint')?.textContent=isAdmin?'Masukkan username dan password admin.':'Masukkan username kasir tanpa password.';$('username')?.focus()}
async function login(){try{const username=($('username')?.value||'').trim().toLowerCase(),password=loginMode==='admin'?($('password')?.value||''):'';if(!username)return toast('Masukkan username terlebih dahulu.');if(loginMode==='admin'&&!password)return toast('Password admin wajib diisi.');let session=await ensureSession();currentUser=session.user;let result=await sb.rpc('kiosk_login',{p_username:username,p_password:password||null});if(result.error&&/JWT|session|anonymous|not authenticated/i.test(result.error.message||'')){await sb.auth.signOut();session=await ensureSession();currentUser=session.user;result=await sb.rpc('kiosk_login',{p_username:username,p_password:password||null})}if(result.error)throw result.error;const data=result.data;if(!data?.length)throw Error('Username tidak ditemukan atau tidak aktif.');const account=data[0];if(loginMode==='admin'&&account.role!=='admin')throw Error('Akun ini bukan akun admin.');if(loginMode==='kasir'&&account.role==='admin')throw Error('Gunakan tombol Login Admin untuk akun admin.');const prof=await sb.rpc('kiosk_profile',{p_username:account.username});if(prof.error)throw prof.error;if(!prof.data?.length)throw Error('Profil akun belum tersedia.');profile=prof.data[0];profile.auth_user_id=currentUser.id;if(!profile.aktif)throw Error('Akun tidak aktif.');localStorage.setItem('tokokasirherbal-username',profile.username);showApp();try{await loadAll()}catch(loadErr){console.error('loadAll after login',loadErr);toast('Login berhasil, tetapi data belum dapat dimuat: '+(loadErr?.message||'periksa RLS/data Supabase'));}}catch(e){console.error('login',e);const m=String(e?.message||e);if(/anonymous|disabled|sign.?in/i.test(m))toast('Login otomatis Supabase gagal. Aktifkan Anonymous Sign-Ins di Supabase Authentication.');else toast(m||'Login gagal')}}
async function loadProfileByUsername(username){const {data,error}=await sb.rpc('kiosk_profile',{p_username:username});if(error)throw error;if(!data?.length)throw Error('Profil akun belum tersedia.');profile=data[0]}
async function restoreLogin(){showLogin()}
async function logout(){try{localStorage.removeItem('tokokasirherbal-username');if(sb)await sb.auth.signOut()}finally{location.reload()}}
async function loadProfile(){if(!currentUser?.id)throw Error('Sesi login tidak valid.');const {data,error}=await sb.from('users').select('*').eq('auth_user_id',currentUser.id).maybeSingle();if(error)throw error;if(!data)throw Error('Profile pengguna belum dibuat di public.users.');profile=data}
function showLogin(){$('app')?.classList.add('hidden');$('login')?.classList.remove('hidden')}
function showApp(){$('login')?.classList.add('hidden');$('app')?.classList.remove('hidden');$('activeUser').textContent=(profile?.role==='admin'?'Admin':'Kasir')+' Aktif: '+(profile?.nama||profile?.username||'-');updateAccountView();const admin=String(profile?.role||'').toLowerCase()==='admin';$('navLaporan').style.display=admin?'block':'none';$('navAkun').style.display=admin?'block':'none';$('navPembelian').style.display=admin?'block':'none';$('addProductBtn').style.display=admin?'block':'none';$('addAgentBtn').style.display=admin?'block':'none'}
function tab(name,el){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$('tab-'+name).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));el?.classList.add('active')}
async function loadAll(){const base=[sb.from('products').select('*').eq('aktif',true).order('nama'),sb.from('agents').select('*').eq('aktif',true).order('nama'),sb.from('receivables').select('*, agents(nama), sales(nomor_transaksi,created_at)').order('created_at',{ascending:false})];if(profile?.role==='admin'){base.push(sb.from('sales').select('*').order('created_at',{ascending:false}).limit(500),sb.from('purchases').select('*').order('created_at',{ascending:false}).limit(500),sb.from('users').select('id,username,nama,role,aktif,created_at,updated_at,auth_user_id').order('nama'));}const results=await Promise.all(base);for(const x of results)if(x.error)throw x.error;const [p,a,r,s,pu,u]=results;products=p.data||[];agents=a.data||[];receivables=r.data||[];sales=profile?.role==='admin'?(s?.data||[]):[];purchases=profile?.role==='admin'?(pu?.data||[]):[];users=profile?.role==='admin'?(u?.data||[]):[];renderAll()}
function renderAll(){renderProducts();renderAgents();renderReceivables();renderReports();renderPurchases();renderUsers();fillAgentSelect();fillPurchaseProducts();renderCart();renderPurchaseCart()}
function renderProducts(){const q=$('search').value.toLowerCase(),cat=$('category').value;const list=products.filter(p=>p.nama.toLowerCase().includes(q)&&(cat==='Semua'||p.kategori===cat));const cats=[...new Set(list.map(p=>p.kategori))];const rakNames={Kapsul:'Produk Agarillus',Cair:'Produk Herbal Biasa',Madu:'Rak 1',Serbuk:'Rak 2',Lainnya:'Rak 3'};$('products').innerHTML=cats.map(c=>`<div class="rak"><h3>📦 ${esc(rakNames[c]||c)}</h3><div class="grid">${list.filter(p=>p.kategori===c).map(p=>`<div class="product" onclick="choosePrice('${p.id}')"><button class="edit ${profile?.role==='admin'?'':'hidden'}" onclick="event.stopPropagation();openProduct('${p.id}')">✏️</button><img src="${escAttr(p.gambar||'')}" onerror="this.src='https://placehold.co/300x180?text=Herbal'"><div class="info"><b>${esc(p.nama)}</b><div class="price">${rp(p.harga_ecer)}</div><div class="stock">Sisa Stok: ${p.stok}</div></div></div>`).join('')}</div></div>`).join('')||'<div class="note">Produk belum tersedia.</div>'}
function choosePrice(id){priceProduct=products.find(p=>p.id===id);if(!priceProduct||priceProduct.stok<=0)return toast('Stok habis.');$('priceName').textContent=priceProduct.nama;$('priceButtons').innerHTML=[['ecer','Harga Ecer',priceProduct.harga_ecer],['reseller','Harga Reseller',priceProduct.harga_reseller],['agen','Harga Agen',priceProduct.harga_agen],['grosir','Harga Grosir',priceProduct.harga_grosir]].map(x=>`<button class="btn pricepick" onclick="addCart('${x[0]}')"><small>${x[1]}</small><br><b class="price">${rp(x[2])}</b></button>`).join('');openModal('priceModal')}
function addCart(type){const p=priceProduct;if(!p)return;const key=p.id+'-'+type,existing=cart.find(x=>x.key===key),same=cart.filter(x=>x.id===p.id).reduce((a,x)=>a+x.qty,0);if(same>=p.stok)return toast('Stok maksimum tercapai.');if(existing)existing.qty++;else cart.push({key,id:p.id,nama:p.nama,qty:1,type,harga:Number(p['harga_'+type])||0});closeModal('priceModal');renderCart()}
function changeQty(key,d){const i=cart.find(x=>x.key===key);if(!i)return;const p=products.find(x=>x.id===i.id);if(!p)return;if(d>0){const same=cart.filter(x=>x.id===i.id).reduce((a,x)=>a+x.qty,0);if(same>=p.stok)return toast('Stok tidak cukup.')}i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.key!==key);renderCart()}
function renderCart(){const total=cart.reduce((a,x)=>a+x.harga*x.qty,0);$('cart').innerHTML=cart.length?cart.map(x=>`<div class="cartitem"><div><b>${esc(x.nama)}</b><div class="note">${x.qty} × ${rp(x.harga)} (${x.type})</div><strong class="price">${rp(x.harga*x.qty)}</strong></div><div class="qty"><button onclick="changeQty('${x.key}',-1)">−</button> ${x.qty} <button onclick="changeQty('${x.key}',1)">+</button></div></div>`).join(''):'<div class="note empty">Keranjang kosong.</div>';$('total').textContent=rp(total);changeAmount()}
function paymentChanged(){const p=$('payment').value==='piutang';$('cashFields').classList.toggle('hidden',p);$('debtFields').classList.toggle('hidden',!p)}
function changeAmount(){if($('payment').value!=='tunai')return;const total=cart.reduce((a,x)=>a+x.harga*x.qty,0),cash=Number($('cash').value||0);$('change').textContent=cash?'Kembalian: '+rp(cash-total):'';$('change').style.color=cash<total?'var(--danger)':'var(--p)'}
async function checkout(){try{if(!cart.length)return toast('Keranjang kosong.');const total=cart.reduce((a,x)=>a+x.harga*x.qty,0),metode=$('payment').value,dibayar=metode==='tunai'?Number($('cash').value||0):Number($('dp').value||0),agent=metode==='piutang'?$('agentForSale').value:null;if(metode==='tunai'&&dibayar<total)return toast('Uang tunai kurang.');if(metode==='piutang'&&!agent)return toast('Pilih agen.');const {data,error}=await sb.rpc('create_sale',{p_kasir_id:profile.id,p_agent_id:agent||null,p_metode:metode,p_dibayar:dibayar,p_items:cart.map(x=>({product_id:x.id,qty:x.qty,tipe_harga:x.type}))});if(error)throw error;toast('Transaksi '+data.nomor_transaksi+' berhasil.');cart=[];$('cash').value='';$('dp').value='';await loadAll()}catch(e){console.error(e);toast(e.message||'Transaksi gagal')}}
function fillAgentSelect(){$('agentForSale').innerHTML='<option value="">Pilih agen</option>'+agents.map(a=>`<option value="${a.id}">${esc(a.nama)}${a.hp?' — '+esc(a.hp):''}</option>`).join('')}
function renderAgents(){$('agents').innerHTML=agents.map(a=>`<tr><td>${esc(a.nama)}</td><td>${esc(a.hp||'-')}</td><td>${esc(a.alamat||'-')}</td><td>${profile?.role==='admin'?`<button class="btn danger" onclick="deleteAgent('${a.id}')">Hapus</button>`:''}</td></tr>`).join('')}
async function saveAgent(){try{if(profile?.role!=='admin')return toast('Hanya admin yang dapat menambah agen.');const nama=$('aNama').value.trim(),hp=$('aHp').value.trim(),alamat=$('aAlamat').value.trim();if(!nama)return toast('Nama wajib diisi.');const {data,error}=await sb.from('agents').insert({nama,hp,alamat}).select().single();if(error)throw error;if(!data)throw Error('Agen tidak berhasil disimpan.');closeModal('agentModal');$('aNama').value=$('aHp').value=$('aAlamat').value='';await loadAll();toast('Agen berhasil ditambahkan.')}catch(e){console.error('saveAgent',e);toast('Gagal menyimpan agen: '+(e.message||'periksa RLS Supabase'))}}
async function deleteAgent(id){if(profile?.role!=='admin')return toast('Hanya admin yang dapat menghapus agen.');if(!confirm('Nonaktifkan agen ini?'))return;const {data,error}=await sb.from('agents').update({aktif:false}).eq('id',id).select().single();if(error)toast(error.message);else{await loadAll();toast('Agen dinonaktifkan.')}}
function renderReceivables(){$('receivables').innerHTML=receivables.map(r=>`<tr><td>${esc(r.sales?.nomor_transaksi||'-')}</td><td>${esc(r.agents?.nama||'-')}</td><td>${new Date(r.created_at).toLocaleDateString('id-ID')}</td><td>${rp(r.total)}</td><td>${rp(r.dibayar)}</td><td><b style="color:${r.sisa?'var(--danger)':'var(--p)'}">${r.sisa?rp(r.sisa):'LUNAS'}</b></td><td>${r.sisa?`<button class="btn primary" onclick="payDebt('${r.id}',${r.sisa})">Bayar</button>`:''}</td></tr>`).join('')}
async function payDebt(id,sisa){const v=prompt('Nominal pembayaran',String(sisa));if(!v)return;const amount=Number(v);if(!Number.isFinite(amount)||amount<=0)return toast('Nominal pembayaran tidak valid.');try{const {error}=await sb.rpc('pay_receivable',{p_receivable_id:id,p_kasir_id:profile.id,p_jumlah:amount,p_keterangan:'Pembayaran piutang'});if(error)throw error;await loadAll();toast('Pembayaran piutang berhasil.')}catch(e){toast(e.message)}}
function renderReports(){
 const now=new Date(), day=now.toISOString().slice(0,10), month=day.slice(0,7);
 const ds=sales.filter(s=>String(s.created_at).slice(0,10)===day), ms=sales.filter(s=>String(s.created_at).slice(0,7)===month);
 const income=ds.reduce((a,s)=>a+Number(s.total||0),0), mincome=ms.reduce((a,s)=>a+Number(s.total||0),0);
 $('income').textContent=rp(income); $('sold').textContent=ds.length+' transaksi'; $('stock').textContent=products.reduce((a,p)=>a+Number(p.stok||0),0)+' Pcs';
 if($('monthIncome'))$('monthIncome').textContent=rp(mincome); if($('monthSold'))$('monthSold').textContent=ms.length+' transaksi';
 $('sales').innerHTML=ds.map(s=>`<tr><td>${new Date(s.created_at).toLocaleString('id-ID')}</td><td>${esc(s.nomor_transaksi)}</td><td>${rp(s.total)}</td><td>${esc(s.metode_pembayaran)}</td></tr>`).join('')||'<tr><td colspan="4" class="note">Belum ada penjualan hari ini.</td></tr>';
 if($('monthlySales')) $('monthlySales').innerHTML=ms.map(s=>`<tr><td>${new Date(s.created_at).toLocaleDateString('id-ID')}</td><td>${esc(s.nomor_transaksi)}</td><td>${rp(s.total)}</td><td>${esc(s.metode_pembayaran)}</td></tr>`).join('')||'<tr><td colspan="4" class="note">Belum ada penjualan bulan ini.</td></tr>';
}
function updateAccountView(){const w=$('accountWelcome'),em=$('accountEmail'),ei=$('accountEmailInput');if(w)w.textContent=(profile?.nama||'Akun')+' (@'+(profile?.username||'-')+')';if(em)em.textContent='Login: '+(profile?.username||'-');if(ei)ei.value='Username: '+(profile?.username||'-')}
function openAccount(){if(!profile)return;if(!$('accountModal'))return toast('Panel akun belum tersedia.');$('accountNama').value=profile.nama||'';$('accountUsername').value=profile.username||'';$('accountEmailInput').value='Username: '+(profile.username||'');openModal('accountModal')}
async function setUserPassword(id){if(profile?.role!=='admin')return toast('Hanya admin yang dapat mengubah password.');const u=users.find(x=>x.id===id);if(!u||u.role!=='admin')return toast('Password hanya diperlukan untuk akun admin.');const p=prompt('Password baru untuk '+u.username);if(p===null)return;if(p.length<4)return toast('Password minimal 4 karakter.');const {error}=await sb.rpc('admin_set_password',{p_user_id:id,p_password:p});if(error)toast(error.message);else toast('Password admin berhasil diubah.')}
function openNewUser(){if(profile?.role!=='admin')return toast('Hanya admin yang dapat menambah akun.');$('newUserNama').value='';$('newUserUsername').value='';$('newUserRole').value='karyawan';$('newUserPassword').value='';$('newUserPassword').placeholder='Kosongkan untuk kasir';openModal('newUserModal')}
async function saveNewUser(){if(profile?.role!=='admin')return toast('Hanya admin yang dapat menambah akun.');const nama=$('newUserNama').value.trim(),username=$('newUserUsername').value.trim().toLowerCase(),role=$('newUserRole').value,password=$('newUserPassword').value;if(!nama||!username)return toast('Nama dan username wajib diisi.');if(role==='admin'&&password.length<4)return toast('Password admin minimal 4 karakter.');if(role==='karyawan'&&password)return toast('Kasir tidak menggunakan password.');const {error}=await sb.rpc('admin_create_user',{p_username:username,p_nama:nama,p_role:role,p_password:password||null});if(error)toast(error.message);else{closeModal('newUserModal');await loadAll();toast('Akun '+(role==='admin'?'admin':'kasir')+' berhasil dibuat.')}}
async function saveAccount(){try{const nama=$('accountNama').value.trim(),username=$('accountUsername').value.trim().toLowerCase();if(!nama)return toast('Nama wajib diisi.');if(!/^[a-z0-9._-]{3,30}$/.test(username))return toast('Username 3-30 karakter: huruf, angka, titik, garis bawah atau strip.');const {data,error}=await sb.rpc('kiosk_update_account',{p_nama:nama,p_username:username});if(error)throw error;if(!data?.length)throw Error('Akun tidak berhasil diperbarui.');profile=data[0];localStorage.setItem('tokokasirherbal-username',username);$('activeUser').textContent='Kasir Aktif: '+profile.nama;closeModal('accountModal');await loadAll();toast('Akun berhasil diperbarui.')}catch(e){console.error('saveAccount',e);toast('Gagal memperbarui akun: '+(e.message||'periksa database'))}}
function renderUsers(){if(profile?.role!=='admin'){$('users').innerHTML='';return}$('users').innerHTML=users.map(u=>`<tr><td>${esc(u.nama)}</td><td>${esc(u.username||'-')}</td><td><select onchange="changeRole('${u.id}',this.value)" ${u.id===profile.id?'disabled':''}><option value="karyawan" ${u.role==='karyawan'?'selected':''}>Kasir</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select></td><td>${u.aktif?'Aktif':'Nonaktif'}</td><td>${u.id!==profile.id?`<button class="btn secondary" onclick="toggleUser('${u.id}',${!u.aktif})">${u.aktif?'Nonaktifkan':'Aktifkan'}</button><button class="btn secondary" style="margin-left:6px" onclick="setUserPassword('${u.id}')">Password</button>`:'Saya'}</td></tr>`).join('')}
async function changeRole(id,role){if(profile?.role!=='admin')return toast('Hanya admin yang dapat mengubah role.');if(!['admin','karyawan'].includes(role))return toast('Role tidak valid.');if(id===profile.id&&role!=='admin')return toast('Admin aktif tidak dapat menurunkan role dirinya sendiri.');const {error}=await sb.rpc('admin_update_user',{p_user_id:id,p_role:role,p_aktif:true});if(error)toast(error.message);else{await loadAll();toast('Role berhasil diperbarui.')}}
async function toggleUser(id,aktif){if(profile?.role!=='admin')return toast('Hanya admin yang dapat mengubah status akun.');if(id===profile.id)return toast('Akun yang sedang digunakan tidak dapat dinonaktifkan.');const u=users.find(x=>x.id===id);if(!u)return toast('Akun tidak ditemukan.');const {error}=await sb.rpc('admin_update_user',{p_user_id:id,p_role:u.role,p_aktif:aktif});if(error)toast(error.message);else{await loadAll();toast(aktif?'Akun diaktifkan.':'Akun dinonaktifkan.')}}
function openProduct(id){if(profile?.role!=='admin')return toast('Hanya admin yang dapat mengelola produk.');const p=id?products.find(x=>x.id===id):null;const deleteBtn=$('deleteProductBtn');if(deleteBtn)deleteBtn.classList.toggle('hidden',!p);selectedProductImage=p?.gambar||'';$('productTitle').textContent=p?'Edit Produk':'Produk Baru';$('productId').value=p?.id||'';$('pNama').value=p?.nama||'';$('pEcer').value=p?.harga_ecer||0;$('pReseller').value=p?.harga_reseller||0;$('pAgen').value=p?.harga_agen||0;$('pGrosir').value=p?.harga_grosir||0;$('pStok').value=p?.stok||0;$('pKategori').value=p?.kategori||'Kapsul';$('pGambar').value=p?.gambar&&!p.gambar.startsWith('data:image/')?p.gambar:'';const fileInput=$('pGambarFile');if(fileInput)fileInput.value='';const preview=$('pGambarPreview');if(preview){if(p?.gambar){preview.src=p.gambar;preview.classList.remove('hidden')}else{preview.src='';preview.classList.add('hidden')}}openModal('productModal')}
function previewProductImage(event){const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){event.target.value='';return toast('File harus berupa gambar.')}if(file.size>8*1024*1024){event.target.value='';return toast('Ukuran gambar maksimal 8 MB.')}const reader=new FileReader();reader.onload=()=>{const preview=$('pGambarPreview');if(preview){preview.src=reader.result;preview.classList.remove('hidden')}};reader.onerror=()=>toast('Gagal membaca gambar.');reader.readAsDataURL(file)}
function compressImage(file,max=900,quality=.76){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality))};img.src=reader.result};reader.readAsDataURL(file)})}
async function saveProduct(){try{if(profile?.role!=='admin')return toast('Hanya admin yang dapat menyimpan produk.');const nama=$('pNama').value.trim();if(!nama)return toast('Nama produk wajib diisi.');const nums=['pEcer','pReseller','pAgen','pGrosir','pStok'].map(id=>Number($(id).value||0));if(nums.some(v=>!Number.isFinite(v)||v<0))return toast('Harga dan stok harus berupa angka nol atau lebih.');const [harga_ecer,harga_reseller,harga_agen,harga_grosir,stok]=nums;let gambar=$('pGambar').value.trim()||selectedProductImage;const fileInput=$('pGambarFile'),file=fileInput?.files?.[0];if(file){toast('Mengolah gambar...');gambar=await compressImage(file);if(gambar.length>900000)gambar=await compressImage(file,700,.65);if(gambar.length>1400000)throw Error('Gambar masih terlalu besar. Pilih gambar yang lebih kecil.')}const row={nama,harga_ecer,harga_reseller,harga_agen,harga_grosir,stok,kategori:$('pKategori').value||'Lainnya',gambar,aktif:true};const id=$('productId').value;let q=id?sb.from('products').update(row).eq('id',id):sb.from('products').insert(row);const {data,error}=await q.select().single();if(error)throw error;if(!data)throw Error('Produk tidak berhasil disimpan.');closeModal('productModal');selectedProductImage='';await loadAll();toast(id?'Produk berhasil diperbarui.':'Produk berhasil ditambahkan.')}catch(e){console.error('saveProduct',e);toast('Gagal menyimpan produk: '+(e.message||'periksa RLS Supabase'))}}
async function deleteProduct(event){try{if(event)event.stopPropagation();if(profile?.role!=='admin')return toast('Hanya admin yang dapat menghapus produk.');const id=$('productId').value;if(!id)return toast('Produk belum dipilih.');const nama=$('pNama').value.trim()||'produk ini';if(!confirm('Hapus produk "'+nama+'"? Produk akan dihapus dari daftar penjualan.'))return;const {data,error}=await sb.from('products').update({aktif:false}).eq('id',id).select().single();if(error)throw error;if(!data)throw Error('Produk tidak berhasil dihapus.');closeModal('productModal');selectedProductImage='';await loadAll();toast('Produk berhasil dihapus.')}catch(e){console.error('deleteProduct',e);toast('Gagal menghapus produk: '+(e.message||'periksa RLS Supabase'))}}
function openAgent(){if(profile?.role!=='admin')return toast('Hanya admin yang dapat menambah agen.');$('aNama').value=$('aHp').value=$('aAlamat').value='';openModal('agentModal')}
function openModal(id){$(id).classList.add('show')}function closeModal(id){$(id).classList.remove('show')}
function printReport(){window.print()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escAttr(s){return esc(s).replace(/javascript:/gi,'')}
window.addEventListener('load',async()=>{try{requireConfig();const box=document.querySelector('#login .login-box');if(box)box.innerHTML='<div style="text-align:center;margin-bottom:22px"><div style="font-size:48px">🌿</div><h1>Herbalinovasi POS</h1><p class="note">Kasir cukup username. Admin gunakan username + password.</p></div><div class="field"><label>Username</label><input id="username" autocomplete="username" placeholder="Contoh: kasir1 atau admin" onkeydown="if(event.key===\'Enter\')login()"></div><div class="field"><label>Password <span class="note">(khusus admin)</span></label><input id="password" type="password" autocomplete="current-password" placeholder="Kosongkan jika kasir" onkeydown="if(event.key===\'Enter\')login()"></div><button class="btn primary" style="width:100%" onclick="login()">Masuk ke Aplikasi →</button>';showLogin()}catch(e){console.error('init',e);showLogin();toast(e.message||'Aplikasi gagal dimuat')}})
function openPurchase(){if(profile?.role!=='admin')return toast('Hanya admin yang dapat mencatat pembelian.');$('purchaseDate').value=new Date().toISOString().slice(0,10);fillPurchaseProducts();renderPurchaseCart();openModal('purchaseModal')}
function fillPurchaseProducts(){$('purchaseProduct').innerHTML='<option value="">Pilih produk</option>'+products.map(p=>`<option value="${p.id}">${esc(p.nama)} — stok ${p.stok}</option>`).join('')}
function addPurchaseItem(){const id=$('purchaseProduct').value,qty=Number($('purchaseQty').value||0),harga=Number($('purchasePrice').value||0);if(!id||qty<=0||harga<0)return toast('Pilih produk dan isi qty/harga beli.');const p=products.find(x=>x.id===id),ex=purchaseCart.find(x=>x.product_id===id);if(ex){ex.qty+=qty;ex.harga_beli=harga}else purchaseCart.push({product_id:id,nama:p.nama,qty,harga_beli:harga});$('purchaseQty').value='1';$('purchasePrice').value='0';renderPurchaseCart()}
function renderPurchaseCart(){$('purchaseCart').innerHTML=purchaseCart.map((x,i)=>`<div class="cartitem"><div><b>${esc(x.nama)}</b><div class="note">${x.qty} × ${rp(x.harga_beli)}</div><strong class="price">${rp(x.qty*x.harga_beli)}</strong></div><button class="btn danger" onclick="purchaseCart.splice(${i},1);renderPurchaseCart()">×</button></div>`).join('')||'<div class="note">Belum ada barang.</div>';const t=purchaseCart.reduce((a,x)=>a+x.qty*x.harga_beli,0);if($('purchaseTotal'))$('purchaseTotal').textContent=rp(t)}
async function savePurchase(){try{if(profile?.role!=='admin')return toast('Hanya admin yang dapat mencatat pembelian.');if(!purchaseCart.length)return toast('Tambahkan barang pembelian.');const {data,error}=await sb.rpc('create_purchase',{p_supplier:$('purchaseSupplier').value.trim(),p_tanggal:$('purchaseDate').value||new Date().toISOString().slice(0,10),p_catatan:$('purchaseNote').value.trim(),p_items:purchaseCart.map(x=>({product_id:x.product_id,qty:x.qty,harga_beli:x.harga_beli}))});if(error)throw error;toast('Pembelian '+data.nomor_pembelian+' berhasil dan stok bertambah.');purchaseCart=[];$('purchaseSupplier').value='';$('purchaseNote').value='';closeModal('purchaseModal');await loadAll()}catch(e){console.error(e);toast('Gagal menyimpan pembelian: '+(e.message||'periksa database'))}}
function renderPurchases(){$('purchases').innerHTML=purchases.map(p=>`<tr><td>${esc(p.nomor_pembelian)}</td><td>${esc(p.tanggal)}</td><td>${esc(p.supplier||'-')}</td><td>${rp(p.total)}</td></tr>`).join('')||'<tr><td colspan="4" class="note">Belum ada pembelian.</td></tr>'}


let deferredInstallPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{
  e.preventDefault();
  deferredInstallPrompt=e;
  const b=$('installBtn');
  if(b)b.classList.remove('hidden');
});
window.addEventListener('appinstalled',()=>{
  deferredInstallPrompt=null;
  const b=$('installBtn');
  if(b)b.classList.add('hidden');
  toast('TokoKasirHerbal berhasil dipasang di HP.');
});
async function installApp(){
  if(!deferredInstallPrompt){
    toast('Jika tombol instal belum muncul, buka menu browser lalu pilih Tambahkan ke layar utama.');
    return;
  }
  deferredInstallPrompt.prompt();
  const choice=await deferredInstallPrompt.userChoice;
  if(choice?.outcome==='accepted')toast('Aplikasi sedang dipasang...');
  deferredInstallPrompt=null;
  const b=$('installBtn');
  if(b)b.classList.add('hidden');
}
if('serviceWorker' in navigator){
  window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('PWA service worker',e)));
}
