const CONFIG=window.APP_CONFIG||{url:'',key:''};
let sb=null,currentUser=null,profile=null,products=[],agents=[],receivables=[],sales=[],users=[],cart=[],priceProduct=null;
const $=id=>document.getElementById(id),rp=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>$('toast').classList.remove('show'),3000)}
function requireConfig(){if(!CONFIG.url||!CONFIG.key){toast('Isi config.js dengan Supabase URL dan publishable/anon key.');throw Error('Supabase config belum diisi')}}
async function login(){try{requireConfig();const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return toast('Email dan kata sandi wajib diisi.');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;currentUser=data.user;await loadProfile();if(!profile||!profile.aktif){await sb.auth.signOut();return toast('Akun belum aktif atau profile belum dibuat.')}showApp();await loadAll()}catch(e){toast(e.message||'Login gagal')}}
async function logout(){if(sb)await sb.auth.signOut();location.reload()}
async function loadProfile(){const {data,error}=await sb.from('users').select('*').eq('auth_user_id',currentUser.id).single();if(error)throw error;profile=data}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');$('activeUser').textContent='Kasir Aktif: '+(profile.nama||'-');$('navLaporan').style.display=profile.role==='admin'?'block':'none';$('navAkun').style.display=profile.role==='admin'?'block':'none';$('addProductBtn').style.display=profile.role==='admin'?'inline-flex':'none';$('addAgentBtn').style.display=profile.role==='admin'?'inline-flex':'none';if($('reportGreeting'))$('reportGreeting').textContent='Selamat datang, '+(profile.nama||'Admin')+' 👋'}
function tab(name,el){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$('tab-'+name).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));el?.classList.add('active')}
async function loadAll(){const [p,a,r,s,u]=await Promise.all([sb.from('products').select('*').eq('aktif',true).order('nama'),sb.from('agents').select('*').eq('aktif',true).order('nama'),sb.from('receivables').select('*, agents(nama), sales(nomor_transaksi,created_at)').order('created_at',{ascending:false}),sb.from('sales').select('*').order('created_at',{ascending:false}).limit(100),sb.from('users').select('*').order('nama')]);for(const x of [p,a,r,s,u])if(x.error)throw x.error;products=p.data||[];agents=a.data||[];receivables=r.data||[];sales=s.data||[];users=u.data||[];renderAll()}
function renderAll(){renderProducts();renderAgents();renderReceivables();renderReports();renderUsers();fillAgentSelect();renderCart()}
function renderProducts(){const q=($('search')?.value||'').toLowerCase(),cat=$('category')?.value||'Semua';const list=products.filter(p=>String(p.nama||'').toLowerCase().includes(q)&&(cat==='Semua'||p.kategori===cat));const cats=[...new Set(list.map(p=>p.kategori))];$('products').innerHTML=cats.map(c=>`<div class="rak"><h3><span>📦 ${esc(c)}</span><span class="note">${list.filter(p=>p.kategori===c).length} produk</span></h3><div class="grid">${list.filter(p=>p.kategori===c).map(p=>{const low=Number(p.stok||0)<=5;return `<div class="product" onclick="choosePrice('${p.id}')"><button class="edit ${profile?.role==='admin'?'':'hidden'}" onclick="event.stopPropagation();openProduct('${p.id}')">✏️</button><img src="${escAttr(p.gambar||'')}" alt="${escAttr(p.nama)}" onerror="this.src='https://placehold.co/600x400/f1f5f9/64748b?text=Produk'"/><div class="info"><b>${esc(p.nama)}</b><div class="price" style="margin-top:5px">${rp(p.harga_ecer)}</div><div class="stock ${low?'low':''}">${low?'⚠️ ':''}Stok: ${Number(p.stok||0)}</div></div></div>`}).join('')}</div></div>`).join('')||'<div class="empty note">📦 Produk belum tersedia.<br>Admin dapat menambahkan produk dari tombol <b>＋ Produk</b>.</div>'}
function choosePrice(id){priceProduct=products.find(x=>x.id===id);if(!priceProduct||priceProduct.stok<=0)return toast('Stok habis.');$('priceName').textContent='Harga • '+priceProduct.nama;$('priceButtons').innerHTML=[['ecer','Harga Ecer',priceProduct.harga_ecer],['reseller','Harga Reseller',priceProduct.harga_reseller],['agen','Harga Agen',priceProduct.harga_agen],['grosir','Harga Grosir',priceProduct.harga_grosir]].map(x=>`<button class="btn secondary" style="min-height:78px;flex-direction:column" onclick="addCart('${x[0]}')"><small>${x[1]}</small><b class="price">${rp(x[2])}</b></button>`).join('');openModal('priceModal')}
function addCart(type){const p=priceProduct;if(!p)return;const key=p.id+'-'+type,existing=cart.find(x=>x.key===key),same=cart.filter(x=>x.id===p.id).reduce((a,x)=>a+x.qty,0);if(same>=p.stok)return toast('Stok maksimum tercapai.');if(existing)existing.qty++;else cart.push({key,id:p.id,nama:p.nama,qty:1,type,harga:Number(p['harga_'+type])||0});closeModal('priceModal');renderCart()}
function changeQty(key,d){const i=cart.find(x=>x.key===key);if(!i)return;const p=products.find(x=>x.id===i.id);if(d>0){const same=cart.filter(x=>x.id===i.id).reduce((a,x)=>a+x.qty,0);if(!p||same>=p.stok)return toast('Stok tidak cukup.')}i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.key!==key);renderCart()}
function renderCart(){const total=cart.reduce((a,x)=>a+x.harga*x.qty,0);$('cart').innerHTML=cart.length?cart.map(x=>`<div class="cartitem"><div><b>${esc(x.nama)}</b><div class="note">${x.qty} × ${rp(x.harga)} • ${esc(x.type)}</div><strong class="price">${rp(x.harga*x.qty)}</strong></div><div class="qty"><button aria-label="Kurangi" onclick="changeQty('${x.key}',-1)">−</button><span>${x.qty}</span><button aria-label="Tambah" onclick="changeQty('${x.key}',1)">+</button></div></div>`).join(''):'<div class="empty note">🛒<br><b>Keranjang masih kosong</b><br>Pilih produk untuk memulai transaksi.</div>';$('total').textContent=rp(total);changeAmount()}
function paymentChanged(){const p=$('payment').value==='piutang';$('cashFields').classList.toggle('hidden',p);$('debtFields').classList.toggle('hidden',!p)}
function changeAmount(){if($('payment').value!=='tunai')return;const total=cart.reduce((a,x)=>a+x.harga*x.qty,0),cash=Number($('cash').value||0);$('change').textContent=cash?'Kembalian: '+rp(cash-total):'';$('change').style.color=cash<total?'var(--danger)':'var(--p2)'}
async function checkout(){try{if(!cart.length)return toast('Keranjang kosong.');const total=cart.reduce((a,x)=>a+x.harga*x.qty,0),metode=$('payment').value,dibayar=metode==='tunai'?Number($('cash').value||0):Number($('dp').value||0),agent=metode==='piutang'?$('agentForSale').value:null;if(metode==='tunai'&&dibayar<total)return toast('Uang tunai kurang.');if(metode==='piutang'&&!agent)return toast('Pilih agen.');const {data,error}=await sb.rpc('create_sale',{p_kasir_id:profile.id,p_agent_id:agent||null,p_metode:metode,p_dibayar:dibayar,p_items:cart.map(x=>({product_id:x.id,qty:x.qty,tipe_harga:x.type}))});if(error)throw error;toast('✓ Transaksi '+data.nomor_transaksi+' berhasil.');cart=[];$('cash').value='';$('dp').value='';await loadAll()}catch(e){toast(e.message||'Transaksi gagal')}}
function fillAgentSelect(){$('agentForSale').innerHTML='<option value="">Pilih agen</option>'+agents.map(a=>`<option value="${a.id}">${esc(a.nama)}${a.hp?' — '+esc(a.hp):''}</option>`).join('')}
function renderAgents(){$('agents').innerHTML=agents.map(a=>`<tr><td><b>${esc(a.nama)}</b></td><td>${esc(a.hp||'-')}</td><td>${esc(a.alamat||'-')}</td><td>${profile?.role==='admin'?`<button class="btn danger" onclick="deleteAgent('${a.id}')">Hapus</button>`:'-'}</td></tr>`).join('')||'<tr><td colspan="4" class="empty note">Belum ada agen.</td></tr>'}
async function saveAgent(){try{const nama=$('aNama').value.trim();if(!nama)return toast('Nama wajib diisi.');const {error}=await sb.from('agents').insert({nama,hp:$('aHp').value.trim(),alamat:$('aAlamat').value.trim()});if(error)throw error;closeModal('agentModal');$('aNama').value=$('aHp').value=$('aAlamat').value='';await loadAll();toast('Agen berhasil ditambahkan.')}catch(e){toast(e.message)}}
async function deleteAgent(id){if(!confirm('Hapus agen?'))return;const {error}=await sb.from('agents').delete().eq('id',id);if(error)toast(error.message);else{await loadAll();toast('Agen dihapus.')}}
function renderReceivables(){$('receivables').innerHTML=receivables.map(r=>`<tr><td><b>${esc(r.sales?.nomor_transaksi||'-')}</b></td><td>${esc(r.agents?.nama||'-')}</td><td>${new Date(r.created_at).toLocaleDateString('id-ID')}</td><td>${rp(r.total)}</td><td>${rp(r.dibayar)}</td><td><span class="badge ${r.sisa?'warn':'ok'}">${r.sisa?rp(r.sisa):'LUNAS'}</span></td><td>${r.sisa?`<button class="btn primary" onclick="payDebt('${r.id}',${r.sisa})">Bayar</button>`:'-'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty note">Tidak ada data piutang.</td></tr>'}
async function payDebt(id,sisa){const v=prompt('Nominal pembayaran',String(sisa));if(!v)return;try{const n=Number(v);if(n<=0)return toast('Nominal tidak valid.');const {error}=await sb.rpc('pay_receivable',{p_receivable_id:id,p_kasir_id:profile.id,p_jumlah:n,p_keterangan:'Pembayaran piutang'});if(error)throw error;await loadAll();toast('Pembayaran piutang berhasil.')}catch(e){toast(e.message)}}
function renderReports(){const income=sales.reduce((a,s)=>a+Number(s.total||0),0),low=products.filter(p=>Number(p.stok||0)<=5).length;$('income').textContent=rp(income);$('sold').textContent=sales.length+' transaksi';$('stock').textContent=products.reduce((a,p)=>a+Number(p.stok||0),0)+' Pcs';if($('lowStock'))$('lowStock').textContent=low;$('sales').innerHTML=sales.map(s=>`<tr><td>${new Date(s.created_at).toLocaleString('id-ID')}</td><td><b>${esc(s.nomor_transaksi)}</b></td><td>${esc(profile?.nama||'-')}</td><td>${rp(s.total)}</td><td><span class="badge ${s.metode_pembayaran==='tunai'?'ok':'warn'}">${esc(s.metode_pembayaran)}</span></td></tr>`).join('')||'<tr><td colspan="5" class="empty note">Belum ada transaksi.</td></tr>'}
function renderUsers(){$('users').innerHTML=users.map(u=>`<tr><td><b>${esc(u.nama)}</b></td><td>${esc(u.username||'-')}</td><td><select onchange="changeRole('${u.id}',this.value)" ${profile?.role==='admin'?'':'disabled'}><option value="karyawan" ${u.role==='karyawan'?'selected':''}>Kasir</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select></td><td><span class="badge ${u.aktif?'ok':'warn'}">${u.aktif?'Aktif':'Nonaktif'}</span></td><td>${profile?.role==='admin'&&u.id!==profile.id?`<button class="btn secondary" onclick="toggleUser('${u.id}',${!u.aktif})">${u.aktif?'Nonaktifkan':'Aktifkan'}</button>`:'-'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty note">Belum ada profile user.</td></tr>'}
async function changeRole(id,role){const {error}=await sb.from('users').update({role}).eq('id',id);if(error)toast(error.message);else{await loadAll();toast('Role berhasil diperbarui.')}}
async function toggleUser(id,aktif){const {error}=await sb.from('users').update({aktif}).eq('id',id);if(error)toast(error.message);else{await loadAll();toast(aktif?'User diaktifkan.':'User dinonaktifkan.')}}
function openProduct(id){if(profile?.role!=='admin')return;const p=id?products.find(x=>x.id===id):null;$('productTitle').textContent=p?'Edit Produk':'Produk Baru';$('productId').value=p?.id||'';$('pNama').value=p?.nama||'';$('pEcer').value=p?.harga_ecer||0;$('pReseller').value=p?.harga_reseller||0;$('pAgen').value=p?.harga_agen||0;$('pGrosir').value=p?.harga_grosir||0;$('pStok').value=p?.stok||0;$('pKategori').value=p?.kategori||'Kapsul';$('pGambar').value=p?.gambar||'';$('pGambarFile').value='';if(p?.gambar){$('pGambarPreview').src=p.gambar;$('pGambarPreview').classList.remove('hidden')}else{$('pGambarPreview').src='';$('pGambarPreview').classList.add('hidden')}openModal('productModal')}
function previewProductImage(event){const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return toast('File harus berupa gambar.');if(file.size>8*1024*1024)return toast('Ukuran gambar maksimal 8 MB.');const reader=new FileReader();reader.onload=()=>{$('pGambarPreview').src=reader.result;$('pGambarPreview').classList.remove('hidden')};reader.readAsDataURL(file)}
function compressImage(file,max=900,quality=.78){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality))};img.src=reader.result};reader.readAsDataURL(file)})}
async function saveProduct(){try{const nama=$('pNama').value.trim();if(!nama)return toast('Nama produk wajib diisi.');let gambar=$('pGambar').value.trim();const file=$('pGambarFile').files?.[0];if(file){toast('Mengolah gambar...');gambar=await compressImage(file);if(gambar.length>900000)gambar=await compressImage(file,700,.68)}const row={nama,harga_ecer:Number($('pEcer').value||0),harga_reseller:Number($('pReseller').value||0),harga_agen:Number($('pAgen').value||0),harga_grosir:Number($('pGrosir').value||0),stok:Number($('pStok').value||0),kategori:$('pKategori').value,gambar,aktif:true};const id=$('productId').value;let q=id?sb.from('products').update(row).eq('id',id):sb.from('products').insert(row);const {error}=await q;if(error)throw error;closeModal('productModal');await loadAll();toast(id?'Produk berhasil diperbarui.':'Produk berhasil ditambahkan.')}catch(e){toast(e.message||'Gagal menyimpan produk')}}
function openAgent(){openModal('agentModal')}
function openModal(id){$(id).classList.add('show')}
function closeModal(id){$(id).classList.remove('show')}
function printReport(){window.print()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function escAttr(s){return esc(s).replace(/javascript:/gi,'')}
window.addEventListener('load',()=>{try{requireConfig();sb=supabase.createClient(CONFIG.url,CONFIG.key,{auth:{persistSession:false,autoRefreshToken:true,detectSessionInUrl:false}})}catch(e){toast(e.message)}})
