/* Username-only kiosk login. No password. Anonymous Auth is only the technical Supabase session. */
(function(){
  const KKEY='tokokasirherbal-kiosk-user';
  const q=id=>document.getElementById(id);
  const client=()=>window.supabase.createClient(window.APP_CONFIG.url,window.APP_CONFIG.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'tokokasirherbal-auth'}});
  function setLoginUI(){const box=document.querySelector('#login .login-box');if(!box)return;box.innerHTML='<div style="text-align:center;margin-bottom:22px"><div style="font-size:46px">🌿</div><h1 style="margin:8px 0">Herbalinovasi POS</h1><p class="note">Masuk dengan nama akun. Tidak perlu password.</p></div><div class="field"><label>Nama Akun</label><input id="kioskUsername" autocomplete="username" placeholder="Contoh: admin" onkeydown="if(event.key===\'Enter\')kioskLogin()"></div><button class="btn primary" style="width:100%;font-size:16px;padding:12px" onclick="kioskLogin()">Masuk</button>'}
  async function ensureSession(){requireConfig();window.sb=client();sb=window.sb;let s=(await sb.auth.getSession()).data.session;if(s)return s;const r=await sb.auth.signInAnonymously();if(r.error)throw new Error('Gagal membuat sesi Supabase: '+r.error.message);if(!r.data?.session)throw new Error('Supabase tidak mengembalikan sesi.');return r.data.session}
  async function kioskLogin(){try{const u=(q('kioskUsername')?.value||'').trim().toLowerCase();if(!u)return window.toast('Masukkan nama akun.');const s=await ensureSession();currentUser=s.user;const {data,error}=await sb.rpc('kiosk_login',{p_username:u});if(error)throw error;if(!data?.length)throw new Error('Akun tidak ditemukan atau nonaktif.');localStorage.setItem(KKEY,u);await kioskLoadProfile();showApp();await loadAll()}catch(e){console.error(e);window.toast(e.message||'Login gagal')}}
  async function kioskRestore(){try{requireConfig();window.sb=client();sb=window.sb;const u=localStorage.getItem(KKEY);if(!u){setLoginUI();return}const s=(await sb.auth.getSession()).data.session;if(!s){localStorage.removeItem(KKEY);setLoginUI();return}currentUser=s.user;const {data,error}=await sb.rpc('kiosk_login',{p_username:u});if(error||!data?.length){localStorage.removeItem(KKEY);await sb.auth.signOut();setLoginUI();return}await kioskLoadProfile();if(!profile?.aktif){localStorage.removeItem(KKEY);await sb.auth.signOut();setLoginUI();return}showApp();await loadAll()}catch(e){console.error(e);localStorage.removeItem(KKEY);setLoginUI()}}
  async function kioskLogout(){localStorage.removeItem(KKEY);if(window.sb?.auth)await window.sb.auth.signOut();location.reload()}
  async function kioskLoadProfile(){const u=localStorage.getItem(KKEY);if(!u)throw Error('Akun belum dipilih.');const {data,error}=await sb.rpc('kiosk_profile',{p_username:u});if(error)throw error;if(!data?.length)throw Error('Profile akun belum tersedia.');profile=data[0]}
  window.kioskLogin=kioskLogin;window.kioskLogout=kioskLogout;window.login=kioskLogin;window.logout=kioskLogout;
  window.addEventListener('load',()=>setTimeout(()=>{if(!window.APP_CONFIG?.url||!window.APP_CONFIG?.key||!window.supabase?.createClient)return;setLoginUI();kioskRestore()},100));
})();
