/* Username-only kiosk login. No password. Uses Anonymous Auth only as a technical Supabase session. */
(function(){
  const KKEY='tokokasirherbal-kiosk-user';
  const q=id=>document.getElementById(id);
  const client=()=>window.supabase.createClient(window.APP_CONFIG.url,window.APP_CONFIG.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'tokokasirherbal-auth'}});
  function setLoginUI(){const box=document.querySelector('#login .login-box');if(!box)return;box.innerHTML='<div style="text-align:center;margin-bottom:22px"><div style="font-size:46px">🌿</div><h1 style="margin:8px 0">Herbalinovasi POS</h1><p class="note">Masuk dengan nama akun. Tidak perlu password.</p></div><div class="field"><label>Nama Akun</label><input id="kioskUsername" autocomplete="username" placeholder="Contoh: admin" onkeydown="if(event.key===\'Enter\')kioskLogin()"></div><button class="btn primary" style="width:100%;font-size:16px;padding:12px" onclick="kioskLogin()">Masuk</button>'}
  async function ensureSession(){window.sb=client();let s=(await window.sb.auth.getSession()).data.session;if(s)return s;const r=await window.sb.auth.signInAnonymously();if(r.error)throw new Error('Supabase Anonymous Auth gagal: '+r.error.message);if(!r.data?.session)throw new Error('Supabase tidak mengembalikan session.');return r.data.session}
  async function kioskLogin(){try{const u=(q('kioskUsername')?.value||'').trim().toLowerCase();if(!u)return window.toast('Masukkan nama akun.');const s=await ensureSession();window.currentUser=s.user;const {data,error}=await window.sb.rpc('kiosk_login',{p_username:u});if(error)throw error;if(!data?.length)throw new Error('Akun tidak ditemukan atau nonaktif.');localStorage.setItem(KKEY,u);await window.loadProfile();window.showApp();await window.loadAll()}catch(e){console.error(e);window.toast(e.message||'Gagal masuk')}}
  async function kioskRestore(){try{window.sb=client();const u=localStorage.getItem(KKEY);if(!u){setLoginUI();return}const s=(await window.sb.auth.getSession()).data.session;if(!s){localStorage.removeItem(KKEY);setLoginUI();return}window.currentUser=s.user;const {data,error}=await window.sb.rpc('kiosk_login',{p_username:u});if(error||!data?.length){localStorage.removeItem(KKEY);await window.sb.auth.signOut();setLoginUI();return}await window.loadProfile();if(!window.profile?.aktif){localStorage.removeItem(KKEY);await window.sb.auth.signOut();setLoginUI();return}window.showApp();await window.loadAll()}catch(e){console.error(e);localStorage.removeItem(KKEY);setLoginUI()}}
  async function kioskLogout(){localStorage.removeItem(KKEY);if(window.sb?.auth)await window.sb.auth.signOut();location.reload()}
  async function kioskLoadProfile(){const u=localStorage.getItem(KKEY);if(!u)throw Error('Akun belum dipilih.');const {data,error}=await window.sb.from('users').select('*').eq('username',u).maybeSingle();if(error)throw error;if(data){window.profile=data;return}const {data:a,error:ae}=await window.sb.rpc('kiosk_profile',{p_username:u});if(ae)throw ae;if(!a?.length)throw Error('Profile akun belum tersedia.');window.profile=a[0]}
  window.kioskLogin=kioskLogin;window.kioskLogout=kioskLogout;window.login=kioskLogin;window.logout=kioskLogout;window.loadProfile=kioskLoadProfile;
  window.addEventListener('load',()=>setTimeout(()=>{if(!window.APP_CONFIG?.url||!window.APP_CONFIG?.key||!window.supabase?.createClient)return;setLoginUI();kioskRestore()},100));
})();
